name = "xia"
description = "Implements XPath 1.0 in Ada"
version = "1.3.1"
licenses= "GPL-3.0-or-later"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

project-files = ["XIA.gpr"]

[[depends-on]]
gnat   = ">11.0.0"
xmlada = "^21.0.0"

[gpr-externals]
LIBRARY_TYPE = ["static", "relocatable"]
